experiment_name: "radargesture"
training:
  batch_size: 256
  epochs: 100
  run_id: "250805_01"
  use_amp: false
  gradient_clip: 1.0
  seed: 1
  optimizer: 
    name: "adamw"
    learning_rate: 0.0001
    weight_decay: 0.01
  scheduler:
    name: "none" #"cosine"
    warmup_epochs: 5
data:
  dataset_path: '/home/phd_li/jeremy/dataset/dataset_transformed_none/'
  input_channels: 3
  output_classes: 6
  pin_memory: false
  num_workers: 8
  persistent_workers: true
  prefetch_factor: 4
  drop_last: true
