experiment_name: "radargesture"
training:
  batch_size: 32
  epochs: 100
  run_id: "run_test_2"
  use_amp: false
  gradient_clip: 1.0
  seed: 1
  optimizer: 
    name: "adamw"
    learning_rate: 0.0001
    weight_decay: 0.01
  scheduler:
    name: "none" #"cosine"
    warmup_epochs: 5
data:
  # dataset_path: '/home/swadiryus/projects/dataset_debug/'
  dataset_path: '/home/swadiryus/projects/dataset_transformed/'
  input_channels: 3
  output_classes: 5
  pin_memory: false
  num_workers: 4
  persistent_workers: true
  prefetch_factor: 4
  drop_last: true
