experiment_name: "radargesture"
training:
  batch_size: 32
  epochs: 100
  run_id: "250801_01"
  use_amp: true
  gradient_clip: 1.0
  seed: 1
  optimizer: 
    name: "adamw"
    learning_rate: 0.001
    weight_decay: 0.01
  scheduler:
    name: "none" #"cosine"
    warmup_epochs: 5
data:
  dataset_path: '/home/phd_li/dataset/radar_gesture_dataset/fulldataset/'
  input_channels: 3
  output_classes: 5
  pin_memory: false
  num_workers: 0
  persistent_workers: true
  prefetch_factor: 4
  drop_last: true
