experiment_name: "radargesture"
training:
  batch_size: 2048
  epochs: 2
  run_id: "test"
  use_amp: false
  gradient_clip: 1.0
  seed: 1
  optimizer: 
    name: "adamw"
    learning_rate: 0.001
    weight_decay: 0.01
  scheduler:
    name: "none" #"cosine"
    warmup_epochs: 5
data:
  dataset_path: '/home/phd_li/jeremy/dataset_npy/'
  input_channels: 3
  output_classes: 5
  pin_memory: false
  num_workers: 1
  persistent_workers: true
  prefetch_factor: 4
  drop_last: true
