experiment_name: "radargesture"
training:
  batch_size: 2
  epochs: 2
  run_id: "test"
  use_amp: true
  gradient_clip: 1.0
  seed: 1
  optimizer: 
    name: "adamw"
    learning_rate: 0.001
    weight_decay: 0.01
  scheduler:
    name: "none" #"cosine"
    warmup_epochs: 5
data:
  # dataset_path: '/home/swadiryus/projects/dataset_debug/'
  dataset_path: '/home/swadiryus/projects/data_convert_time/'
  input_channels: 3
  output_classes: 5
  pin_memory: false
  num_workers: 0
  persistent_workers: false
  prefetch_factor: 
  drop_last: true
